# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Patch react-native-fast-encoder to use the correct header
# Not sure where the FastEncoderModuleSpec.h is supposed to come from?
def patch_react_native_fast_encoder
  rnfe = Dir.glob(File.join(Pod::Config.instance.installation_root, "..", "node_modules", "react-native-fast-encoder", "ios", "FastEncoderModule.h")).first
  if rnfe
    File.write(rnfe, <<-EOF
#ifdef __cplusplus
#import "react-native-fast-encoder.h"
#endif

#import <React/RCTBridgeModule.h>

@interface FastEncoderModule : NSObject <RCTBridgeModule>
@property (nonatomic, assign) BOOL setBridgeOnMainQueue;

@end
    EOF
    )

    Pod::UI.puts "Patched react-native-fast-encoder".green
  else
    Pod::UI.puts "Could not find react-native-fast-encoder".red
  end
end

target 'BusinessCards-Connect' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    patch_react_native_fast_encoder()
  end
end
